### ISSUE TITLE
Modify backend to remember settings

### ISSUE THREAD

**Issue by Radu-Raicea** [Radu-Raicea/SignalAndroid#129]
User Story #127 

Estimated Time: 4h

**Comment by Dan-Yoo** [comment]
Implementation / Investigation time : 7h

Repost of commit msg: Initially we wanted to synchronize the compression setting in a conversation as to send and receive compressed mms messages if a user desired so. This however was deemed impossible to do as per following the expiring message example (synchronized expiring message when a user selects a time). This example showed us that a modification of another repository is required to modify the core message object. Due to this limitation, it was decided that we would just allow compression from the user who sets it. 

Because of this, my commit was limited as i tried to find a way to implement this but was unable to.
