### ISSUE TITLE
Change nickname displaying throughout the app

### ISSUE THREAD

**Issue by Radu-Raicea** [Radu-Raicea/SignalAndroid#35]
As an user, I want to see the selected nickname in every instance I would see the username.

[SP: 3]
[Priority: High]
[Risk: High]

1. #40 : Modify the name getter to take the nickname if it is set, otherwise get contact

Total: 3h

**Comment by veken1199** [comment]
@Dan-Yoo Acceptance Tests ????

**Comment by veken1199** [comment]
@Dan-Yoo Screenshots

**Comment by Dan-Yoo** [comment]
TASK | INPUTS | EXPECTED OUTPUT | STATUS
-- | -- | -- | --
Display nickname in conversation list view | list of recipients with nicknames set | Conversation list view displays user's nickname instead of name or address | PASS
Display nickname in conversation view | recipient with nickname | menu bar in  conversation view displays recipient's nickname | PASS
Display nickname in recipient preference setting view | recipient with nickname | all reference to name or  address in view is changed to nickname | PASS

**Comment by Dan-Yoo** [comment]
![nickname_convo_list_view](https://user-images.githubusercontent.com/10817632/36950418-9f481e0a-1fc3-11e8-8d64-8895aabe6484.png)

**Comment by Dan-Yoo** [comment]
![nickname_convo_view](https://user-images.githubusercontent.com/10817632/36950420-a458af9a-1fc3-11e8-815b-2a2c214fd6f1.png)

**Comment by Dan-Yoo** [comment]
![nickname_preference_view](https://user-images.githubusercontent.com/10817632/36950423-a7d6c2d8-1fc3-11e8-9dc8-769a6650f890.png)

**Comment by veken1199** [comment]
Implementation time : 2h
